# Generated by Django 3.2.6 on 2021-12-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permalink',
            field=models.SlugField(max_length=25, unique=True),
        ),
    ]