# Generated by Django 3.2.6 on 2022-01-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_permalink'),
        ('user', '0002_user_is_staff'),
    ]

    operations = [
    ]
