# Generated by Django 3.2.6 on 2022-01-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='path',
            field=models.TextField(blank=True),
        ),
    ]
