# Generated by Django 3.2.6 on 2021-12-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_id',
        ),
    ]
