# Generated by Django 3.2.6 on 2021-12-06 11:30

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permalink',
            field=models.CharField(default=user.models.create_permalink, max_length=25, unique=True),
        ),
    ]
