# Generated by Django 3.2.6 on 2021-12-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_follow'),
        ('user', '0009_user_permalink'),
    ]

    operations = [
    ]
