# Generated by Django 3.2.6 on 2021-11-27 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commented_at', models.TimeField(default='00:00')),
                ('parent_comment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='comment.comment')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.track')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
