# Generated by Django 3.2.6 on 2022-01-01 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.track'),
        ),
    ]
