# Generated by Django 3.2.6 on 2022-01-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_parent_comment'),
        ('comment', '0002_initial'),
    ]

    operations = [
    ]
