# Generated by Django 3.2.6 on 2022-01-04 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20220103_1033'),
        ('comment', '0004_alter_comment_commented_at'),
    ]

    operations = [
    ]
