# Generated by Django 3.2.6 on 2022-01-01 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('set', '0001_initial'),
        ('track', '0001_initial'),
        ('tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='set',
            name='tags',
            field=models.ManyToManyField(related_name='sets', to='tag.Tag'),
        ),
        migrations.AddField(
            model_name='set',
            name='tracks',
            field=models.ManyToManyField(related_name='sets', to='track.Track'),
        ),
        migrations.AddConstraint(
            model_name='set',
            constraint=models.UniqueConstraint(fields=('creator', 'permalink'), name='set_permalink_unique'),
        ),
    ]
