# Generated by Django 3.2.6 on 2021-12-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='permalink',
            field=models.CharField(default='something', max_length=255),
            preserve_default=False,
        ),
    ]
