# Generated by Django 3.2.6 on 2021-12-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('set', '0001_initial'),
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='tracks',
            field=models.ManyToManyField(related_name='sets', to='track.Track'),
        ),
    ]
