# Generated by Django 3.2.6 on 2021-12-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0002_set_tracks'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='set',
            constraint=models.UniqueConstraint(fields=('creator', 'permalink'), name='set_permalink_unique'),
        ),
    ]
