# Generated by Django 3.2.6 on 2021-12-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0003_set_set_permalink_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='permalink',
            field=models.SlugField(max_length=255),
        ),
    ]