# Generated by Django 3.2.6 on 2022-01-06 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_alter_track_permalink'),
        ('set', '0004_alter_set_permalink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='tracks',
        ),
        migrations.CreateModel(
            name='SetTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_tracks', to='set.set')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_tracks', to='track.track')),
            ],
        ),
    ]
