# Generated by Django 3.2.6 on 2022-01-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0005_set_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='tracks',
        ),
    ]
