# Generated by Django 3.2.6 on 2022-01-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0007_settrack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='image',
            new_name='image_profile',
        ),
        migrations.AddField(
            model_name='set',
            name='image_header',
            field=models.URLField(null=True, unique=True),
        ),
    ]
