# Generated by Django 3.2.6 on 2022-01-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0005_auto_20220106_0607'),
        ('set', '0007_settrack'),
    ]

    operations = [
    ]
