# Generated by Django 3.2.6 on 2022-01-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_alter_track_permalink'),
        ('set', '0009_rename_image_info_set_image_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='image_profile',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='set',
            name='image_header',
        ),
        migrations.AddField(
            model_name='set',
            name='tracks',
            field=models.ManyToManyField(related_name='sets', through='set.SetTrack', to='track.Track'),
        ),
    ]
