# Generated by Django 3.2.6 on 2022-01-23 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('set', '0010_auto_20220113_0753'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_hit', models.DateTimeField(auto_now=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set.set')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_hit',),
            },
        ),
        migrations.AddConstraint(
            model_name='sethit',
            constraint=models.UniqueConstraint(fields=('user', 'set'), name='set_hit_unique'),
        ),
        migrations.AddField(
            model_name='set',
            name='players',
            field=models.ManyToManyField(related_name='played_sets', through='set.SetHit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='set',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre_sets', to='tag.tag'),
        ),
        migrations.AlterField(
            model_name='set',
            name='tags',
            field=models.ManyToManyField(related_name='tag_sets', to='tag.Tag'),
        ),
    ]
