# Generated by Django 3.2.6 on 2021-12-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set(),
        ),
    ]