# Generated by Django 3.2.6 on 2021-12-18 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('track', '0002_track_permalink'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre_tracks', to='tag.tag'),
        ),
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='tags',
            field=models.ManyToManyField(related_name='tag_tracks', to='tag.Tag'),
        ),
    ]
