# Generated by Django 3.2.6 on 2021-12-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_alter_track_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('artist', 'permalink'), name='track_permalink_unique'),
        ),
    ]