# Generated by Django 3.2.6 on 2021-12-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_auto_20211218_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.URLField(),
        ),
    ]
