# Generated by Django 3.2.6 on 2021-12-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_alter_track_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.URLField(null=True, unique=True),
        ),
    ]
