# Generated by Django 3.2.6 on 2021-12-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_auto_20211221_1104'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('artist', 'permalink'), name='track_permalink_unique'),
        ),
    ]
