# Generated by Django 3.2.6 on 2022-01-22 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('track', '0005_auto_20220122_0601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackhit',
            options={'ordering': ('-last_hit',)},
        ),
        migrations.RemoveField(
            model_name='trackhit',
            name='created_at',
        ),
        migrations.AddField(
            model_name='track',
            name='players',
            field=models.ManyToManyField(related_name='played_tracks', through='track.TrackHit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trackhit',
            name='count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackhit',
            name='last_hit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trackhit',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='track.track'),
        ),
        migrations.AddConstraint(
            model_name='trackhit',
            constraint=models.UniqueConstraint(fields=('user', 'track'), name='track_hit_unique'),
        ),
        migrations.AlterField(
            model_name='trackhit',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.track'),
        ),
        migrations.AlterField(
            model_name='trackhit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
